name: snakesandladders
description: Snakes and Ladders by Wajiha - 100% free fun game.
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.2
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sl_logo.png
    - assets/wajiha_logo.png

  fonts:
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond.ttf
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader.ttf
